### ISSUE TITLE
Reviewer/Reviewee Survey

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding#101]
Last year we conducted an [survey](https://docs.google.com/forms/d/e/1FAIpQLSduLWz8Vtwj7fmAULOnGvk4MKfliHAZnhzH78hVxFTC-xsnEw/viewform) for participants in the review process to inform our [Year in Reviews](https://ropensci.org/blog/2016/03/28/software-review).  I'd like to repeat it. Some of the information no longer needs to be asked because we are [automatically tracking it](https://htmlpreview.github.io/?https://github.com/ropensci/onboarding/blob/7fc10c7fd72fb80e2e9e2a30097c43c289b4a35c/posts/2017-01-16-year-in-reviews.html). What else should we ask about?

Thoughts:
  - What automated checks were useful, and which ones would you like?
  - How useful are the guides and what should be added/removed?
  - What packaging guidelines should be updated?

@gvwilson Has suggested we look at how much people feel multiple reviews provide overlap, based on [previous knowledge](https://smartbear.com/SmartBear/media/pdfs/best-kept-secrets-of-peer-code-review.pdf) that there's diminishing returns in finding bugs (though our reviews do a lot more that find bugs - we look at UI, documentation, etc.).

**Comment by sckott** [comment]
Sounds good. 

Those questions sound good. 

for _What packaging guidelines should be updated?_ we should mention we won't necessarily use suggestions, but we may

**Comment by sckott** [comment]
I think it's worth asking about multiple reviews - since right now we have a pretty low submission rate, but it could pick up in which case we may want to drop to 1 reviewer per submission

**Comment by noamross** [comment]
@karthik

**Comment by stefaniebutland** [comment]
Without adding too many questions, I'd like to ask/hear WHY people submitted their pkg for review, what was their perceived benefit, would they do it again or recommend to someone else?
This gets at people's idea of what value they get from rOpenSci.

**Comment by masalmon** [comment]
@stefaniebutland's comment makes me wonder whether we already ask people how they discovered rOpenSci onboarding system?

**Comment by jsta** [comment]
Do people list rOpenSci reviews alongside journal article reviews in CVs etc?

**Comment by karthik** [comment]
I really hope people do list this on their CVs. I like this:
> What automated checks were useful, and which ones would you like?
because it helps us determine what to improve upon and which ones to skip.

**Comment by kbenoit** [comment]
This may qualify more as the sort of response you are seeking to the survey, than to the design of the survey itself, but two thoughts relating to things raised in the comments above.

 On **multiple reviews**:

* I think it's is really important to solicit multiple views on a package, since this brings multiple perspectives to bear on a package, and since people (usually) disagree in some way. For instance, a package might have a very technical aspect, and an end-user facing aspect. Two reviews allow both sides to be addressed. Yes this is a burden, but it makes the peer review process serious, as it should be, and sends this signal to those judging the worth of successful onboarding, either as as a potential contributor or as a user of an onboarded package.

On the guidelines:

* Having reviewed two packages now and read reviews of many others, I think the main difficulty in reviewing is the indeterminacy between the application of the "usefulness/overlap" issue  - call this a substantive concern - versus the how it's executive issue, call this procedural. 

    Procedural issues are fairly easy to address in guidelines. Substantive issues are much harder either to prescribe in guidelines, or to apply given guidelines. Hardly any package doesn't overlap with some other package, so how much penalty should be applied for redundancy? What if the goal of the package is for a very limited purpose or audience? Thus far, reviews have tended to be very liberal on substantive judgements. Should this change?

And here's a new issue to consider: Should the review process be single- or double- blinded? It's certainly worth asking if it should be single-blinded. How can we trust a review to be tough when toughness is warranted, if he or she is worried about being perceived a buzzkill hard-ass not just by the reviewer but also by the entire rOpenSci community subscribed to the updates? And it's really hard to be tough, since you are pissing on someone's hard work and genuine, commendable desire to contribute something to a community for free, and after running through a straightjacket of checks far more stringent than even the CRAN requirements. Tough one.

**Comment by noamross** [comment]
Thanks for the input, @kbenoit. I'm not going to respond directly here because this thread is about the survey design, but these are both good points and the type of feedback we are looking for. We'll dive into this more post-survey over on the [forum](discuss.ropensci.org).
