### ISSUE TITLE
Doctr: Pre-Submission Inquiry

### ISSUE THREAD

**Issue by ctlente** [ropensci/onboarding#110]
This is a pre-submission of the [`doctr`](https://github.com/ctlente/doctr) package. I'd just like to know if I should consider going for the formal submission or whether the package doesn't fit rOpenSci's guidelines.

### Summary

-   What does this package do? (explain in 50 words or less):
`doctr` fits in rOpenSci's "reproducibility" category and its main goal is to automate EDA workflows while at the same time making them reproducible, predictable and consistent. Like a real doctor, it has functions for examining, diagnosing and assessing the progress of its "patients".

-   URL for the package (the development repository, not a stylized html page):
[https://github.com/ctlente/doctr](https://github.com/ctlente/doctr)

-   Who is the target audience?  
Anyone who needs reproducible and consistent exploratory analysis workflows.

-   Are there other R packages that accomplish the same thing? If so, what is different about yours?  
`assertr` has some similar goals and functions, but they end up complementing themselves very nicely. While `assertr` gives you granular control over a dataset's structure, `doctr`'s broader scope allows it to create full EDAs and even compare two different datasets.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [ ] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration with Travis CI and/or another service.

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [ ] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? Please describe any exceptions:
It doesn't have a `NEWS` file since it was only submitted to CRAN once.

**Comment by noamross** [comment]
Hi @ctlente.  Thanks for your pre-submission and sorry for the slow reply. After a fair bit of back-and-forth amongst the editors, we've decided that we're not going to include EDA in the "reproducibility" category. Reproducibility for us includes pipelining, build, testing, and versioning tools but not end-points like EDA because we think the "right" EDA is too subjective and context-dependent for us to evaluate what are best-in-class tools.  We're working on updating and clarifying our fit policies to include this.

We encourage you to submit to [JOSS](http://joss.theoj.org/), and hope you submit other work to us in the future!

**Comment by ctlente** [comment]
Ok, thanks for your time!
