### ISSUE TITLE
geoops: geospatial operations for GeoJSON data

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding#134]
### Summary

-   What does this package do? (explain in 50 words or less):

`geoops` does spatial operations on GeoJSON data. 

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: geoops
Type: Package
Title: 'GeoJSON' Manipulation Operations
Description: 'GeoJSON' manipulation/calculations/etc, what not,
    stuff, and things.
Version: 0.0.6.9210
Authors@R: c(person("Scott", "Chamberlain", role = c("aut", "cre"),
    email = "myrmecocystus@gmail.com"))
License: MIT + file LICENSE
URL: https://github.com/ropenscilabs/geoops
BugReports: https://github.com/ropenscilabs/geoops/issues
Imports:
    Rcpp (>= 0.12.9)
Suggests:
    roxygen2 (>= 6.0.1),
    testthat,
    knitr,
    rmarkdown
LinkingTo: Rcpp
SystemRequirements: C++11
Roxygen: list(markdown = TRUE)
VignetteBuilder: knitr
RoxygenNote: 6.0.1
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/ropenscilabs/geoops

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

__geospatial data__, because the package works with geospatial data

-   Who is the target audience?  

R users that work primarily or sometimes with GeoJSON data. It's a geospatial data format that's increasingly in use due to it's ubiquity in browsers/javascript - and can be stored in SQL and NoSQL databases.  Preliminary benchmarks show that it's comparable to `rgeos` wrt speed, so users won't suffer any performance hit using this. 

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

`rgeos` is similar - but is meant to handle "spatial R classes" - S4 classes defining spatial objects - users can convert various input formats (wkt, geojson, etc.) to those formats. `geoops` focuses just on geojson, so no conversions to other formats are required. 

We also maintain [lawn](https://github.com/ropensci/lawn) - that wraps turf.js via `V8` - that is a fine pkg, but does present problems for some users as V8 engine may not be easy to install or have the right version.  `geoops` will likely be faster than `lawn`, so speed is a consideration. 

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses. __needs to be filled out more for sure__
- [x] has a test suite. __needs to be filled out more for sure__
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coeveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package contains a [`paper.md`](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

definitely @ateucher as he's already having a look at it
others: @mdsumner @jhollist 
maybe @jeroen to check over C++ stuff

**Comment by sckott** [comment]
Notes: 

- one goal with `geoops` is for me to learn C++.  - so it may not be the prettiest c++ you've ever seen, and happy to get any c++ advice/suggestions
- `geoops` is a port of the Javascript library [turf.js](http://turfjs.org/). There's clearly diff target users for the JS version and R versions. We also maintain [lawn](https://github.com/ropensci/lawn) that wraps turf.js itself via the `V8` package 
- i haven't implemented all of turf's methods in `geoops`  - i probably will eventually, but want to get feedback at an early-ish stage

**Comment by noamross** [comment]
Thanks for your submission, @sckott!

### Editor checks:

- [x] **Fit**: The package meets criteria for [fit](policies.md#fit) and [overlap](policies.md#fit)
- [x] **Automated tests:** Package has a testing suite and is tested via Travis-CI or another CI service.
- [x] **License:** The package has a CRAN or OSI accepted license
- [x] **Repository:** The repository link resolves correctly
- [ ] **Archive** (JOSS only, may be post-review): The repository DOI resolves correctly
- [ ] **Version** (JOSS only, may be post-review): Does the release version given match the GitHub release (v1.0.0)?

---

#### Editor comments

I note the package README says the package is in "alpha stage".  Packages should be relatively stable at review so that reviewers have a stable repository for review and so that they are reviewing the expected API and capabilities at release.  If you think this is so, than remove this text and I'll seek reviewers, otherwise, we can hold until you think you are at "beta".  In addition:

- Add a code coverage badge to your README.
- Since this package has compiled code, add Windows CI testing
- The README and vignette are both quite very sparse terms of explanatory text, though comprehensive in terms of usage examples. This is reasonably a matter of style if you think the API is largely self-documenting . I will ask the reviewers to pay careful attention to documentation. 

Here is `goodpractice::gp()` output.  I note coverage is low, but this is in large part due to the inclusion of the header library `json.h`. The `covr::package_coverage(line_exclusions=...)` argument can be used in `.travis.yml` to clear this up. Reviewers should look at uncovered areas in your custom code (which is why a badge link to the coverage report is helpful).
```
── GP geoops ────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all
    package code in general. 55% of code lines are
    covered by test cases.

    R/zzz.R:2:NA
    R/zzz.R:3:NA
    R/zzz.R:5:NA
    src/along.cpp:20:NA
    src/along.cpp:21:NA
    ... and 801 more lines

  ✖ use '<-' for assignment instead of '='. '<-' is
    the standard, and R users and developers are used
    it and it is easier to read your code for them if
    you use '<-'.

    inst/ignore/cpp_play.R:65:3
    inst/ignore/cpp_play.R:72:6

  ✖ avoid long code lines, it is bad for readability.
    Also, many people prefer editor windows that are
    about 80 characters wide. Try make your lines
    shorter than 80 characters

    inst/ignore/overlay.R:215:1
    inst/ignore/testing.R:177:1
    R/RcppExports.R:33:1
    tests/testthat/test-destination.R:22:1
    tests/testthat/test-get_coords.R:4:1

  ✖ fix this R CMD check NOTE: installed size is
    14.2Mb sub-directories of 1Mb or more: doc 1.2Mb
    img 1.3Mb libs 11.0Mb
```
(The last error appears to be compiler/platform specific, as I got it on linux and not OSX. I also got an infinite recursion error on linux the odd combination of g++-6 and R 3.3.1, which should just serve as a note for reviewers to look for version/platform snafus.)

From devtools::spell_check():
```
doesn                geo_line_distance.Rd:19
```

**Comment by sckott** [comment]
closing and will open a new issue when i improve the things mentioned
