### ISSUE TITLE
Pre Submission Inquiry - refnet

### ISSUE THREAD

**Issue by aurielfournier** [ropensci/onboarding#247]
Hello,

Curious if you would consider the `refnet` package for review. I think it falls under data extraction and munging, but I wanted to check before submitting. 

https://github.com/embruna/refnet2
 
`RefNet` was written to help users of the R statistical computing environment address these challenges. It imports and organizes the output from Web of Science and SCOPUS searches, disambiguate author names and flags any needing additional scrutiny, parses author addresses, and georeferences author institutions. It also generates simple summary bibliometric statistics and maps author locations and coauthorships. Finally, the data can be exported in tidy formats for more in-depth analyses with user-written code or imported into packages such as 'revtools'.

**Comment by maelle** [comment]
:wave: @aurielfournier! Thanks for asking. Yes it'd be in scope, feel free to submit it when it's ready! 😺 

I have a few questions/remarks (not necessary to answer now, but important when submitting)

* If I use the package for dataset1 and then want to use it for dataset2 that's dataset1 with more rows, can I use the results of my disambiguation results on dataset1?

* In DESCRIPTION I see that the package depends on `tidyverse` which is not recommended cf [this post](https://www.tidyverse.org/articles/2018/06/tidyverse-not-for-packages/)

* In DESCRIPTION no need for the "Author" field because it'll be generated automatically from "Authors@R".
