### ISSUE TITLE
Recommended v required guidelines

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding#83]
There are a few areas where recommendations v requirements in our area should be clarified.  One being package import (e.g. https://github.com/ropensci/onboarding/issues/80#issuecomment-259755701).  There was also the licensing issue for US gov't packages, which are currently CC-0.  The guidelines could probably use an update where we do some organization to make them easier to read and have some hierarchy of importance/requirements.

**Comment by karthik** [comment]
Thanks very much for this discussion. Since the onboarding repo is primarily meant as a tracker for package submissions and review, please continue this discussion over at Onboarding meta (https://github.com/ropensci/onboarding-meta) if you believe this is not already resolved here. In the interest of keeping this issue tracker clean, I am closing this repo. 🙏
