### ISSUE TITLE
getCRUCLdata: Download and Use CRU CL2.0 Climatology Data in R

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/onboarding#96]
### Summary

-   What does this package do? (explain in 50 words or less):
The getCRUCLdata package provides two functions that automate downloading and importing CRU CL2.0 climatology data, facilitates the calculation of minimum temperature and maximum temperature, and formats the data into a tidy data frame or a list of raster stack objects for use in an R session or easily exports to a raster format file for use in a geographic information system (GIS).

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: getCRUCLdata
Type: Package
Title: Download and Use CRU CL2.0 Climatology Data in R
Version: 0.1.2
Authors@R: person(given = "Adam", family = "Sparks", email = "adamhsparks@gmail.com", role = c("aut", "cre"))
Description: Provides functions that automate downloading and importing
    University of East Anglia Climate Research Unit (CRU) CL2.0 climatology data
    into R, facilitates the calculation of minimum temperature and maximum
    temperature and formats the data into a tidy data frame or a list of raster
    stack objects for use in an R session.  CRU CL2.0 data are a gridded
    climatology of 1961-1990 monthly means released in 2002 and cover all land
    areas (excluding Antarctica) at 10-minute resolution.  For more
    information see the description of the data provided by the University of
    East Anglia Climate Research Unit,
    <https://crudata.uea.ac.uk/cru/data/hrg/tmc/readme.txt>.
License: MIT + file LICENSE
Depends: R (>= 3.0.0)
Imports:
    curl,
    dplyr,
    plyr,
    purrr (>= 0.2.0),
    raster,
    tidyr,
    utils
LazyData: TRUE
RoxygenNote: 5.0.1
ByteCompile: TRUE
Suggests:
    testthat,
    knitr,
    rmarkdown,
    covr
URL: https://github.com/adamhsparks/getCRUCLdata
BugReports: https://github.com/adamhsparks/getCRUCLdata/issues
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/adamhsparks/getCRUCLdata

-   Who is the target audience?
Anyone interested in using climate data or generating raster files from the CRU CL2.0 data that are easy to use in a GIS

-   Are there other R packages that accomplish the same thing? If so, what is different about yours?
Not that I'm aware of

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version.
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration with Travis CI and/or another service.

#### Publication options

- [x] Do you intend for this package to go on CRAN?
- [x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [x] The package contains a [`paper.md`](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [x] The package is deposited in a long-term repository with the  DOI: https://doi.org/10.5281/zenodo.264405
    - (*Do not submit your package separately to JOSS*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

Ivan Hanigan, https://github.com/ivanhanigan

**Comment by sckott** [comment]
### Editor checks:
- [x] **Fit**: The package meets criteria for [fit](policies.md#fit) and [overlap](policies.md#fit)
- [x] **Automated tests:** Package has a testing suite and is tested via Travis-CI or another CI service. 
- [x] **License:** The package has a CRAN or OSI accepted license
- [x] **Repository:** The repository link resolves correctly
- [x] **Archive** (JOSS only, may be post-review): The repository DOI resolves correctly
- [x] **Version** (JOSS only, may be post-review): Does the release version given match the GitHub release (v1.0.0)?

---

#### Editor comments

Currently seeking reviewers. It's a good fit and not overlapping. 

* Tests do succeed, but take a long time, would be nice to get these to run faster somehow
* Ran `goodpractice::gp()` , but nothing to deal with at this time. 

---

Reviewers: xxx
Due date: xxx

**Comment by adamhsparks** [comment]
@sckott, I'm working on getting the test time down. I've managed to reduce it by 1/2 already and keep the code coverage the same. I'll see what I can do further.

**Comment by sckott** [comment]
thanks @adamhsparks  - thanks for trying!

**Comment by sckott** [comment]
reviewers assigned, see https://github.com/ropensci/onboarding/issues/96#issuecomment-276509383

**Comment by ldecicco-USGS** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [ ] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions in R help
- [ ] **Examples** for all exported functions in R Help that run successfully locally
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and `URL`, `Maintainer` and `BugReports` fields in DESCRIPTION 

>##### Paper (for packages co-submitting to JOSS)
>
>The package contains a `paper.md` with:
>
>- [x] **A short summary** describing the high-level functionality of the software
>- [x] **Authors:**  A list of authors with their affiliations
>- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
>- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Functionality

- [ ] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 

---

### Review Comments

#### Installation

I'm not sure if this is actually an issue with the package, but when I tried to install via CRAN, there was an error via the Windows binary:

```
> install.packages("getCRUCLdata")
Installing package into ‘C:/Users/ldecicco/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.3/getCRUCLdata_0.1.4.zip'
Content type 'application/zip' length 160600 bytes (156 KB)
downloaded 0 bytes

Warning in install.packages :
  downloaded length 0 != reported length 160600
Warning in install.packages :
  error 1 in extracting from zip file
Warning in install.packages :
  cannot open compressed file 'getCRUCLdata/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection
```

I could install via source just fine. This could be an issue with my CRAN mirror or something else...but I haven't experienced it before.

#### Vignette

The first thing I tried to do was run the first example in the vignette, and was unsuccessful:

```
library(getCRUCLdata)
CRU_data <- create_CRU_df(pre = TRUE,
                          pre_cv = TRUE,
                          rd0 = TRUE,
                          tmp = TRUE,
                          dtr = TRUE,
                          reh = TRUE,
                          tmn = TRUE,
                          tmx = TRUE,
                          sunp = TRUE,
                          frs = TRUE,
                          wnd = TRUE,
                          elv = TRUE)
 
Downloading requested data files.
 
Error in .f(.x[[i]], ...) : Too many retries...server may be under load
```

I then tried setting a single parameter to TRUE, and still could not get data to return:

```
CRU_data <- create_CRU_df(pre = TRUE)
 
Downloading requested data files.
 
Error in .f(.x[[i]], ...) : Too many retries...server may be under load
```


#### Examples

I had the same problem running the examples from the help files as running the examples from the vignette.

#### Tests

Similarly, the tests via `testthat` didn't pass with the same error "Too many retries...server may be under load". However, looking at the tests, they looked like appropriate tests. According to Coveralls, there's a 59% coverage on code. This isn't great, but it's not too bad. 


#### Troubleshooting

When I went to the URLs to test the service, they worked fine. I use `httr` for the package `dataRetrieval` (so, not as familiar with `purr`). I tried this:

```
library(httr)

temp <- tempfile()
temp <- paste0(temp,".dat.gz")
obs_url <- "https://crudata.uea.ac.uk/cru/data/hrg/tmc/grid_10min_dtr.dat.gz"
doc <- GET(obs_url, write_disk(temp))

headerInfo <- headers(doc)
doc2 <- read.table(gzfile(temp))

unlink(doc)
```

`doc2` came back as a table with 14 columns and 566262 rows. So, maybe give `httr` a try? As it is, I can't get anything back from the package, and I don't think it's the underlying services fault.

**Comment by sckott** [comment]
Thanks for your review @ldecicco-USGS !

**Comment by adamhsparks** [comment]
Thanks for the review @ldecicco-USGS.

It's interesting. I'm not able to replicate the issue with installation because unfortunately, I don't have a Windows machine to test on, I rely on Winbuilder and Appveyor to alert me to any issues. I checked the zip package from CRAN, if I'm reading the error correctly it says that there was no DESCRIPTION file. However, the zip file I downloaded had one in it.

Moving on to the other items, I'm also unable to replicate the issues. I just ran the code that was pasted here that timed out. It worked and the tests pass on my computer, Travis and Appveyor when downloading, so I assume everything is fine. I wonder if there's a network issue that is causing problems?

I'll look at using `httr`. The `purr` code comes from one of my other packages where the server will stop responding so it limits the number of requests made and I incorporated it here to be nice to this server as well, so I'm stumped about what the issue is.

**Comment by adamhsparks** [comment]
@ldecicco-USGS, I've modified the download function to use `httr::GET` as suggested in the devel branch, if you'd like to check it.

https://github.com/adamhsparks/getCRUCLdata/tree/devel

**Comment by ivanhanigan** [comment]
## Package Review for getCRUCLdata

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [ ] **Function Documentation:** for all exported functions in R help
- [x] **Examples** for all exported functions in R Help that run successfully locally
- [x] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and `URL`, `Maintainer` and `BugReports` fields in DESCRIPTION 

>##### Paper (for packages co-submitting to JOSS)
>
>The package contains a `paper.md` with:
>
>- [x] **A short summary** describing the high-level functionality of the software
>- [x] **Authors:**  A list of authors with their affiliations
>- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
>- [x] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [ ] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 

- 3hrs

---

### Review Comments

This is a useful R package that is well written and provides access to an important data collection. 
I reviewed the Github version, master branch, installed today 21 Feb 2017, on Ubuntu linux.  I made comments against the line numbers for files in the devel branch.
The documentation is clear and attractive.  Functionality on my linux machine is mostly good, with some functionality not working/returning errors.  

#### Major comments

##### test 1 `create_CRU_df`

- Success: I ran the suggested line from README for all 12 parameters and retrieved a df with 6800028 obs, 15 vars, 0.8GB according to object.size()
- Comment re single threaded.  I ran this on a 16 core machine and was disappointed to only see one core spinning.  Is there options for parallelisation?
- Comment re size of download is significant, and any problems (e.g. broken connection with cloud VM, power outage etc) may cause frustration if object is lost due to crashed R session.  I ran save.image() straight after successful 
- Issue re `with(CRU_data, plot(lon, lat))` caused my Rstudio server to return status 502 (unresponsive) and I killed the session.  I tried again, left it running for 30 mins and then logged in to see the plot had completed, but the session was still clunky and I got unresponsive warnings and then I terminated it.  This is a NeCTAR research cloud XXL running on QCIF infrastructure (64GB, 16 core, 2.3 GHz Opterons) so should not have an issue.  Suggest you pack some easily visualisable meta info such as the lat lon points as a small df or spatialPoints obj so is easily plotable.
- Issue re next line causes a warning and fails

```{r}
t_rh <- create_CRU_df(tmp = TRUE,
+                       reh = TRUE)
 
Downloading requested data files.
 
  |=================================================================================================================| 100%
Error in full_join_impl(x, y, by$x, by$y, suffix$x, suffix$y) : 
  'lat' column not found in lhs, cannot join
```  

- Issue re help file for this function, has example but also fails

```{r}
 CRU_pre_tmp <- create_CRU_df(pre = TRUE, tmp = TRUE)
 
Downloading requested data files.
 
  |=================================================================================================================| 100%
Error in full_join_impl(x, y, by$x, by$y, suffix$x, suffix$y) : 
  'lat' column not found in lhs, cannot join
```

##### test 2 `create_CRU_stack`

- Comment re I then went ahead and test create_CRU_stack.  I immediatly realise this is downloading more data, and wondered if seeing as I have a dataframe I previously downloaded it might be possible to just convert that to a stack. To save more downloading.  Converse is also true: if user has already downloaded raster stack (or stored this as local tifs) then perhaps create_CRU_df could be told to use the data that already exists.
- Comment re I see in devel/vignettes/getCRUCLdata.Rmd line 112-115 the useful suggestion to store rasters locally as geotiffs.  Recommend a similar suggestion above for the dataframe.  Also suggest you load the raster library here too, for Noobs who may get upset by the warning if the try to run writeRaster without that package attached.
- Success re CRU_stack.  I ran the following and got successful geotiffs

```{r}
writeRaster(CRU_stack$pre, filename = paste0("~/tmp/pre_", names(CRU_stack$pre)), bylayer = TRUE, format = "GTiff")
writeRaster(CRU_stack$reh, filename = paste0("~/tmp/reh_", names(CRU_stack$reh)), bylayer = TRUE, format = "GTiff")
```

- loaded precip december tif into QGIS succeeds, and is projected as WGS84, thanks.  Value for Darwin of 240 is very close to the Darwin Airport 233.9 reported by the BoM for the same 61-90 period.  Awesome thanks.
- issue re next line from vignettes/getCRUCLdata

```{r}
tmn_tmx <- create_CRU_stack(tmn = TRUE,
                            tmx = TRUE)
Downloading requested data files.
 
  |======================================                                                                           |  33%
Error in raster::crop(y, raster::extent(-180, 180, -60, 85)) : 
  object 'y' not found
							
```							
- Issue re help for this function: "Details This function generates a data.frame object in R with the following possible fields as specified by the user: " should read "raster stack" not data.frame
- Success the example in that help file worked (`CRU_pre_tmp <- create_CRU_stack(pre = TRUE, tmp = TRUE)`)

#### Minor comments

Re devel/README.Rmd: 

- line 34 re '10 minute resolution' - can you say this in decimal degrees to avoid confusion for GIS Noobs (also in devel/vignettes/getCRUCLdata.Rmd, line 19).
- further comment, this appears in the file `devel/man/getCRUdata.Rd` as 10 arc-second, so at least need to resolve which units to declare, but I strongly recommend aligning with decimal degrees.
- line 57 - should read "stable version of getCRUCLdata is available from CRAN" not "GSODR is available"

Re paper.md

- This could have more of a statement of need and audience.  Currently it echos the README but I think here it would be nice to expand a bit of discussion.

Re general

- There might be opportunity to optimise the processing and also provide some safegaurds in terms of automatically storing downloaded data locally to protect users from crashs etc that might lead to them having to download the same data multiple times.
- I did not assess code style, code duplication, Automated tests or Packaging guidelines as I lack the programming expertise for that.
- I checked a couple external URLs which succeed in taking me to the Uni East Anglia pages that describe these data, thanks!


#### My sessionInfo

```{r}
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] getCRUCLdata_0.1.4

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.2.0       assertthat_0.1 DBI_0.5-1      tools_3.3.1    dplyr_0.5.0    tibble_1.2     Rcpp_0.12.9  
```

**Comment by adamhsparks** [comment]
@ivanhanigan Thank you for a thorough and helpful review. 

I've started addressing a few of the more minor issues that you've pointed out in the "devel" branch and will continue to work through these suggestions.

**Comment by sckott** [comment]
thanks for your review @ivanhanigan !

**Comment by adamhsparks** [comment]
@ivanhanigan and @ldecicco-USGS,
I've taken your suggestions from the reviews and incorporated them into the latest release, v0.1.5.

# Highlights
## Major Changes

  * `create_CRU_stack()` and `create_CRU_df()` now only work with locally available files. If you need to fetch and create a data frame or raster stack of the data, please use the new functions, `get_CRU_stack()` and `create_CRU_stack()`
  * R >=3.2.0 now required

## Minor Changes

  * Improved documentation with examples on mapping and graphing and more detail regarding the data itself
  * Change the method in which files are downloaded to use `httr::GET()`
  * Ingest data using `data.table::fread` to decrease the amount of time necessary to run the functions
  * Functions check to see if data file(s) have already been downloaded during current R session, if so data file(s) are not requested for download again
  * Months are returned as a factor object in the tidy data frame

# Detailed discussion

@ivanhanigan:

Regarding the parallelisation. I've intentionally not gone this route due to cross-platform issues and different processors making things difficult with little reward based on experience with another R package. However, I have used `fread` from the `data.table` package to decrease the runtime by ingesting the raw data more quickly. This resulted in a small, but notable decrease in the time necessary to run any of the functions.

Regarding the downloading issues, I've included two new functions that work with local files only and do not rely on R to download the files. Since CRAN guidelines specify that an R package should not write to disk (other than R's `tempfile()` or `tempdisk()`, I've elected to go this route so that a user may use an FTP client, web browser or other means to download and save the files locally before using this package in R. This also is useful for individuals who might desire to use this same data more than once, having the raw data on hand saving the download time and only importing into R from local.

Regarding the saving data when downloading, the functions now only download files that do not exist in the current R session. If you download temperature and create a stack, when creating a data frame of temperature will not trigger a new download unless you restart your R session.

Regarding the `with(CRU_data, plot(lon, lat))`, I've included examples using `ggplot2` to generate maps and graphs in README and vignette, this takes only a few seconds to generate on the machines I have a available to test on.

Regarding the 10 minute (second) issues. I've corrected the documentation and added the values both in arcminutes (the original from New et al.) and as a decimal value of degrees.

I've updated the paper.md file to be more detailed and addressed other comments regarding functionality and documentation as suggested.

Thank you both, @ldecicco-USGS and @ivanhanigan, again for the very constructive and helpful comments. They have helped me make this a much more robust R package that hopefully benefits R users.

**Comment by sckott** [comment]
Thanks for the changes @adamhsparks 

@ivanhanigan @ldecicco-USGS are you two happy with the changes?

**Comment by ivanhanigan** [comment]
Thanks @adamhsparks for the changes.  I am not able to look at this for a
few days, and I cannot check on windows like @ldecicco-USGS reviewed with.
I'll get back to you as soon as I can, probably early next week.
Thanks again Adam.

**Comment by ldecicco-USGS** [comment]
I'll have a look sometime this week! Hopefully this afternoon if meetings pan out as scheduled.

**Comment by adamhsparks** [comment]
Hello @ldecicco-USGS and @ivanhanigan, please don't rush to check these updates. I'm planning more.

I just found out about the `[rappdirs]`(https://github.com/hadley/rappdirs) package looking at @sckott's `ropensci::ccafs` package I'll modify the code to use a persistent cache directory for storing the files. This will take me a week or two I'd guess since I'm pretty busy with "real" work right now.

However, I think that this will provide a much nicer end-user experience.

**Comment by sckott** [comment]
thanks for the update @adamhsparks 

see also https://github.com/ropensci/hoardr which is not quite to cran yet - wraps rappdirs to be a little more user friendly, see eg usage here https://github.com/ropenscilabs/cmipr/blob/master/R/onLoad.R and then you just export and document the caching object https://github.com/ropenscilabs/cmipr/blob/master/R/caching.R created in onload

**Comment by sckott** [comment]
@ldecicco-USGS do you have an estimate for how long your review took (for our records)

**Comment by ldecicco-USGS** [comment]
I'll be happy to look again when @adamhsparks does his next round of updates (see 2 comments up). I think the first round only took ~1 hour.

**Comment by sckott** [comment]
okay, thanks @ldecicco-USGS

**Comment by adamhsparks** [comment]
Ok folks. I've had another go at this.

I've added the ability to cache files in the users' home filespace as I mentioned and cleaned up a few other minor items while I was at it.

Please have another look and let me know of any issues or suggestions.

**Comment by ivanhanigan** [comment]
Adam.
The new README looks great. I'll try to get to this in the next few days.

**Comment by ldecicco-USGS** [comment]
Same here, hopefully today or tomorrow.

**Comment by ivanhanigan** [comment]
Hi Adam thanks for the new release of the `getCRUCLdata` package.
I started a new review BUT have not done a comprehensive review yet.

But thought I'd just check in on something I think is worth discussing re cached files of a one-off download of the data vs repeated downloading on-the-fly. 

When I looked at the code in the readme, it was obvious `~/Downloads' does not work. 
```{r}
t <- create_CRU_df(tmp = TRUE, dsn = "~/Downloads")
```

So I checked the function and found downloading is actually to this directory:
```{r}
dsn <- "/home/ivan_hanigan/.config/getCRUCLdata"
# which works juset as well 
t2 <- create_CRU_df(tmp = TRUE, dsn = dsn)
identical(t, t2)
# TRUE
```

It seems to me that this location will not be very clear to users of the program if asked `where is the CRU data you downloaded as a one-off'?  It seems like the package assumes people will download the data whenever the function is invoked - 'on-the-fly'.

My concern I wanted to raise before proceeding with my review is that data downloading as a 'one-off' might considered more important by the user, and being prompted to choose a place to store the result for further management, versus a 'on-the-fly' data download to a temporary/system location crated for the current session.
This assumes good network connections and there are associated issues with online data provision (including trust that the data provider will not change the data at the online location between downloads) that require soem consideration .

So I just thought I'd flag this issue now and suggest the following:

What about making ` get_CRU` to ask the User where to download the CRU data to?
Then this makes the location explicit and makes the dataset a more recognisable contribution to the files that they have on their system. 

PS I noticed a duplicated chunk of text in this
```{r}
?get_CRU_df
"Duplicated?
# Download data and create a data frame of precipitation and temperature
# without caching the data files
CRU_pre_tmp <- get_CRU_df(pre = TRUE, tmp = TRUE)

# Download data and create a data frame of precipitation and temperature
# without caching the data files
CRU_pre_tmp <- get_CRU_df(pre = TRUE, tmp = TRUE)
"
```
All the best, and I will continue the review this week - in between other work responsibilities.

Thanks Adam!

I

**Comment by adamhsparks** [comment]
Hi @ivanhanigan,
I don't understand why using `create_CRU_df(dsn = "~/Downloads")` won't work as I've illustrated?

It seems to work properly for me, could you give me the line numbers in the code that you think are incorrect? `create_CRU_df()` does not download anything. It requires the data to already exist locally, e.g "~/Downloads".  `get_CRU_df()` downloads to the location you've described and caches.

Is there a need to rename the functions so that the differences are more clear?

PS
You're right. It was a duplicate. I've fixed that.

**Comment by ivanhanigan** [comment]
Hi, 
It is not incorrect but it depends on the user moving the data from the cache_dir to the folder `~/Downloads` in your example.

```
#in README it says 
t <- create_CRU_df(tmp = TRUE, dsn = "~/Downloads")
# but the function get_CRU_df() downloads and caches data in a special directory
# so you probably need to explain to the user
# they need to move/copy the data to the folder they then specified to the dsn argument
# we can find this with 
cachedir <- rappdirs::user_config_dir("getCRUCLdata")
# on my system this is "/home/ivan_hanigan/.config/getCRUCLdata"
# so I can move the files from there to the correct folder, or leave them there 
# (but that seems like sloppy data management to me)
# I just move them to a data folder here
system(sprintf("mv %s/ data_provided/", cachedir))
# and then when I come back to use them I know they are handy
t3 <- create_CRU_df(tmp = TRUE, dsn = "data_provided")
# and identical to what I downloaded fresh with 
t <- get_CRU_df(tmp = TRUE, cache = FALSE)
identical(t, t3)
# TRUE
```
Or do you recommend that users store the raw data in the `.config/getCRUCLdata` location?

**Comment by adamhsparks** [comment]
@ivanhanigan, it's not intended for the user to move data at all. It's intended if a user has network issues, to use an external FTP program was previously suggested.

The caching works only with the `get_CRU_df()` function. If you use that function, you would need to re-use it to take advantage of the caching functionality. Perhaps I should just drop the caching since it seems to be creating confusion?

**Comment by adamhsparks** [comment]
I've tried to revise the README text for clarity.

**Comment by ldecicco-USGS** [comment]
I pulled the latest changes from the master branch here and built from that. When I tried the first example in the vignette:

```
CRU_data <- create_CRU_df(pre = TRUE,
                          pre_cv = TRUE,
                          rd0 = TRUE,
                          tmp = TRUE,
                          dtr = TRUE,
                          reh = TRUE,
                          tmn = TRUE,
                          tmx = TRUE,
                          sunp = TRUE,
                          frs = TRUE,
                          wnd = TRUE,
                          elv = TRUE)
 Error in .validate_dsn(dsn) : 
File directory does not exist: .
```

I thought maybe that was because the vignette maybe is dated? So I tried the first example for that function:
```
CRU_pre_tmp <- create_CRU_df(pre = TRUE, tmp = TRUE, dsn = "~/Downloads")
Error in .validate_dsn(dsn) : 
File directory does not exist: ~/Downloads.
```
So...I need to create some actual path in the dsn argument. I did this:
```
CRU_pre_tmp <- create_CRU_df(pre = TRUE, tmp = TRUE, dsn = "D:/LADData")

Creating data frame now.

  |                                                     |   0%gzip: D:/LADData/ is a directory -- ignored
 Show Traceback
 
 Rerun with Debug
 Error in data.table::fread(paste0("gzip -dc ", .files), header = FALSE) : 
  File is empty: C:\Users\ldecicco\AppData\Local\Temp\1\RtmpszBo52\filefac5fb84c54 In addition: Warning messages:
1: running command 'C:\Windows\system32\cmd.exe /c (gzip -dc D:/LADData/) > C:\Users\ldecicco\AppData\Local\Temp\1\RtmpszBo52\filefac5fb84c54' had status 2 
2: In shell(paste("(", input, ") > ", tt, sep = "")) :
  '(gzip -dc D:/LADData/) > C:\Users\ldecicco\AppData\Local\Temp\1\RtmpszBo52\filefac5fb84c54' execution failed with error code 2
```

So, I think I agree with @ivanhanigan that the documentation on what I'm suppose to put in the `dsn` argument needs to be improved.

**Comment by adamhsparks** [comment]
I don't know what's happened here. That's not the first example in the vignette and the function arguments are not all supplied properly so it won't run and stops as it should?

This is the first example in the vignette:

```r
library(getCRUCLdata)

CRU_data <- get_CRU_df(pre = TRUE,
                       pre_cv = TRUE,
                       rd0 = TRUE,
                       tmp = TRUE,
                       dtr = TRUE,
                       reh = TRUE,
                       tmn = TRUE,
                       tmx = TRUE,
                       sunp = TRUE,
                       frs = TRUE,
                       wnd = TRUE,
                       elv = TRUE,
                       cache = TRUE)
```

**Comment by adamhsparks** [comment]
@ldecicco-USGS,
I've added more description to the documentation, but I still don't understand the first example that you posted. I don't know where that comes from?

Thanks!

**Comment by ivanhanigan** [comment]
Hi again,
I have re-read the README section "Creating tidy data frames for use in R"
and it does make a lot of sense thanks.
I appreciate the way the package is trying to accommodate a variety of
different data downloading/storage/networking scenarios.
I think that you've done a great job of making this flexible for that, but
maybe the additional detail that needs to be discussed for
caching/FTP-FileZilla is confusing and could be put in a later section such
as "advanced usage/special circumstances" section and the more visible
sections of README and vignettes just show the simple application of
running the `get_CRU_df()` function.

Then you could move into a discussion about how useless repeatedly
downloading copies of the same data, OR internet connectivity problems
might lead you to want to use FileZilla or caching?

I'll move on to the next components of the documentation tomorrow.  I think
that if you don't want to make more changes then the current approach to
caching/downloading is adequate.  Up to you mate!

Cheers, Ivan

**Comment by ldecicco-USGS** [comment]
OK, I think what was happening with my first example is that I was using the older version of the vignette. I re-built the vignettes and got things working.

I think where there could be confusion (there was from me at least...), that might easily be straightened out for the user, is have the very first example in the vignette be how to actually download the data. The vignette starts with "Using getCRUCLdata", which is definitely the cool part of the package, but maybe having a section above that "Getting CRUCL Data" with the explicit instruction downloading for the first time would be helpful. Then, all the examples with `cache=TRUE` immediately work.

Otherwise, looks good! 

A minor suggestion that might help people like me (who..maybe...have been known to only skim through the instructions :sweat: )....I kept trying to run `create_CRU_df` without having run `get_CRU_df` first. I saw the "dsn" argument and thought it would _save_ the data there, not _find_ the data there. Perhaps you could put a custom error message in that function, that if the `dsn` argument doesn't have the correct files, to use `get_CRU_df` to download the data?

**Comment by adamhsparks** [comment]
@ldecicco-USGS that's a good suggestion, I'm guilty of skimming documentation too. I'll implement that change.

I'll reorganise the documentation as you and Ivan have suggested. You've both been very helpful, thank you.

**Comment by adamhsparks** [comment]
Hi folks, I've edited the README and vignette to include a quick start and a more advanced section on caching and using `create_CRU_*()` functions.

No changes to functionality, only documentation.

I've also linted the package and fixed some errors in the documentation with typos, "a a", etc.

**Comment by sckott** [comment]
is all taken care of @adamhsparks ? If so, i'll take a final look

**Comment by adamhsparks** [comment]
@sckott, I hope that I've addressed @ldecicco-USGS' and @ivanhanigan's comments re: documentation.

I'm still trying to change the error message when the DSN doesn't exist or files aren't found. The error stops and works, but the issue I'm having is with getting it to pass the test. :/

**Comment by adamhsparks** [comment]
@sckott, I think we're good. I've tidied it up a bit more here and there. Have a look now when you have time.

**Comment by sckott** [comment]
@adamhsparks Looks good to me. approved :) 

i assume you know the drill from here?

**Comment by adamhsparks** [comment]
I do. I've added the footer. I'll wait for the transfer request and update all the links and submit this latest version to CRAN.

Thanks for your time, suggestion and effort @ivanhanigan, @ldecicco-USGS  and @sckott. Once again, the rOpenSci review process really made the package a much better offering.

**Comment by sckott** [comment]
thx for your submission!
